productos_listar:
    path: /api/productos
    controller: AppBundle\Controller\ProductoController::listar
    methods: [GET]
productos_crear:
    path: /api/productos
    controller: AppBundle\Controller\ProductoController::crear
    methods: [POST]
productos_ver:
    path: /api/productos/{id}
    controller: AppBundle\Controller\ProductoController::ver
    methods: [GET]
    requirements: { id: '\d+' }
productos_editar:
    path: /api/productos/{id}
    controller: AppBundle\Controller\ProductoController::editar
    methods: [PUT]
    requirements: { id: '\d+' }
productos_borrar:
    path: /api/productos/{id}
    controller: AppBundle\Controller\ProductoController::borrar
    methods: [DELETE]
    requirements: { id: '\d+' }
productos_composicion:
    path: /api/productos/{id}/composicion
    controller: AppBundle\Controller\ProductoController::composicion
    methods: [GET]
    requirements: { id: '\d+' }
productos_composicion_guardar:
    path: /api/productos/{id}/composicion
    controller: AppBundle\Controller\ProductoController::guardarComposicion
    methods: [PUT]
    requirements: { id: '\d+' }
